/**
 * Quick Take scenarios
 *
 * Tests the Quick Take feature which generates a one-liner AI commentary
 * when a task is created, cross-referencing existing tasks. Unlike other
 * features, quick take returns plain text (a single sentence), not
 * structured JSON.
 *
 * Each scenario provides a newTaskTitle and a set of existing tasks that
 * create a specific context the AI should pick up on.
 */

import type { AITestScenario } from '../types'

export const quickTakeScenarios: AITestScenario[] = [
  // -------------------------------------------------------------------------
  // 1. Cross-reference by project
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-project-crossref',
    feature: 'quick_take',
    description: 'New task matches existing project tasks — should cross-reference by project',
    input: {
      newTaskTitle: 'Draft Acme Q1 report',
      timezone: 'America/Chicago',
      tasks: [
        {
          id: 1,
          title: 'Review Acme contract renewal',
          priority: 2,
          due_at: '2026-02-26T15:00:00Z',
          original_due_at: '2026-02-26T15:00:00Z',
          created_at: '2026-02-20T14:00:00Z',
          labels: [],
          project_name: 'Acme Corp',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 2,
          title: 'Send Acme invoice #4821',
          priority: 1,
          due_at: '2026-02-27T15:00:00Z',
          original_due_at: '2026-02-27T15:00:00Z',
          created_at: '2026-02-22T10:00:00Z',
          labels: [],
          project_name: 'Acme Corp',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 3,
          title: 'Prepare Acme demo environment',
          priority: 0,
          due_at: '2026-02-28T20:00:00Z',
          original_due_at: '2026-02-28T20:00:00Z',
          created_at: '2026-02-23T09:00:00Z',
          labels: [],
          project_name: 'Acme Corp',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 10,
          title: 'Buy groceries',
          priority: 0,
          due_at: '2026-02-25T22:00:00Z',
          original_due_at: '2026-02-25T22:00:00Z',
          created_at: '2026-02-24T12:00:00Z',
          labels: ['errand'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 11,
          title: 'Morning run',
          priority: 0,
          due_at: '2026-02-26T13:00:00Z',
          original_due_at: '2026-02-26T13:00:00Z',
          created_at: '2026-01-01T12:00:00Z',
          labels: ['health'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 12,
          title: 'Call dentist for appointment',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: '2026-02-18T16:00:00Z',
          labels: [],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 13,
          title: 'Update resume',
          priority: 1,
          due_at: '2026-03-01T15:00:00Z',
          original_due_at: '2026-03-01T15:00:00Z',
          created_at: '2026-02-20T10:00:00Z',
          labels: [],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'Should cross-reference the 3 existing Acme Corp tasks. A good response would be ' +
        'something like "you\'ve got 3 other Acme tasks this week" or "Acme week — that makes 4 ' +
        'on the board." Must not be generic ("task added!"). Must reference the Acme project or ' +
        'similar tasks by name/count.',
    },
  },

  // -------------------------------------------------------------------------
  // 2. Cross-reference by timing — busy day
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-busy-day',
    feature: 'quick_take',
    description: 'New task fills up an already busy day — should note the crowding',
    input: {
      newTaskTitle: 'Team standup prep',
      timezone: 'America/Chicago',
      tasks: [
        {
          id: 20,
          title: 'Dentist appointment',
          priority: 2,
          due_at: '2026-02-25T15:00:00Z',
          original_due_at: '2026-02-25T15:00:00Z',
          created_at: '2026-02-15T10:00:00Z',
          labels: ['health'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 21,
          title: 'Submit expense report',
          priority: 1,
          due_at: '2026-02-25T17:00:00Z',
          original_due_at: '2026-02-25T17:00:00Z',
          created_at: '2026-02-20T09:00:00Z',
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 22,
          title: 'Pick up dry cleaning',
          priority: 0,
          due_at: '2026-02-25T20:00:00Z',
          original_due_at: '2026-02-25T20:00:00Z',
          created_at: '2026-02-22T14:00:00Z',
          labels: ['errand'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 23,
          title: 'Review pull request',
          priority: 1,
          due_at: '2026-02-25T21:00:00Z',
          original_due_at: '2026-02-25T21:00:00Z',
          created_at: '2026-02-24T11:00:00Z',
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 30,
          title: 'Weekly grocery run',
          priority: 0,
          due_at: '2026-02-27T15:00:00Z',
          original_due_at: '2026-02-27T15:00:00Z',
          created_at: '2026-02-20T12:00:00Z',
          labels: ['errand'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=WEEKLY;BYDAY=FR',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 31,
          title: 'Read chapter 5',
          priority: 0,
          due_at: '2026-02-28T22:00:00Z',
          original_due_at: '2026-02-28T22:00:00Z',
          created_at: '2026-02-22T10:00:00Z',
          labels: [],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'Should note today (Feb 25) is getting busy — 4 existing tasks due today and now a 5th. ' +
        'A good response: "your Wednesday is filling up — that makes 5 today" or ' +
        '"busy day ahead, you already had 4 things due today." Must reference the count or ' +
        'the busy nature of the day specifically.',
    },
  },

  // -------------------------------------------------------------------------
  // 3. No due date observation
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-no-due-date',
    feature: 'quick_take',
    description: 'New task has no due date — should comment on it sitting in inbox',
    input: {
      newTaskTitle: 'Research standing desks',
      timezone: 'America/Chicago',
      tasks: [
        {
          id: 40,
          title: 'File taxes',
          priority: 3,
          due_at: '2026-03-15T15:00:00Z',
          original_due_at: '2026-03-15T15:00:00Z',
          created_at: '2026-02-01T10:00:00Z',
          labels: ['finance'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 41,
          title: 'Morning standup',
          priority: 0,
          due_at: '2026-02-26T15:00:00Z',
          original_due_at: '2026-02-26T15:00:00Z',
          created_at: '2026-01-01T15:00:00Z',
          labels: ['work'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 42,
          title: 'Call insurance about deductible',
          priority: 1,
          due_at: '2026-02-28T16:00:00Z',
          original_due_at: '2026-02-28T16:00:00Z',
          created_at: '2026-02-18T09:00:00Z',
          labels: [],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 43,
          title: 'Replace furnace filter',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: '2026-02-10T14:00:00Z',
          labels: ['home'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 44,
          title: 'Plan weekend trip',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: '2026-02-15T11:00:00Z',
          labels: [],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 45,
          title: 'Review quarterly goals',
          priority: 2,
          due_at: '2026-03-01T15:00:00Z',
          original_due_at: '2026-03-01T15:00:00Z',
          created_at: '2026-02-20T08:00:00Z',
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'The new task "Research standing desks" has no due date. A good response ' +
        'observes that it will sit in the inbox without a date: "no due date — it\'ll ' +
        'hang out in your inbox until you schedule it" or "joining 2 other undated tasks ' +
        'in your inbox." Could also note the other undated tasks (IDs 43, 44). ' +
        'Must not be generic. Must reference the lack of a due date or inbox placement.',
    },
  },

  // -------------------------------------------------------------------------
  // 4. Solo task in a category
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-solo-category',
    feature: 'quick_take',
    description: 'New task is the only one of its kind — should note its uniqueness',
    input: {
      newTaskTitle: 'Drop off library books',
      timezone: 'America/Chicago',
      tasks: [
        {
          id: 50,
          title: 'Sprint planning meeting',
          priority: 2,
          due_at: '2026-02-25T15:00:00Z',
          original_due_at: '2026-02-25T15:00:00Z',
          created_at: '2026-02-20T09:00:00Z',
          labels: ['work'],
          project_name: 'Platform Team',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 51,
          title: 'Deploy v2.3 to staging',
          priority: 2,
          due_at: '2026-02-25T18:00:00Z',
          original_due_at: '2026-02-25T18:00:00Z',
          created_at: '2026-02-23T14:00:00Z',
          labels: ['work'],
          project_name: 'Platform Team',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 52,
          title: 'Write API docs for auth module',
          priority: 1,
          due_at: '2026-02-26T20:00:00Z',
          original_due_at: '2026-02-26T20:00:00Z',
          created_at: '2026-02-22T11:00:00Z',
          labels: ['work'],
          project_name: 'Platform Team',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 53,
          title: 'Code review: login flow refactor',
          priority: 1,
          due_at: '2026-02-26T17:00:00Z',
          original_due_at: '2026-02-26T17:00:00Z',
          created_at: '2026-02-24T10:00:00Z',
          labels: ['work'],
          project_name: 'Platform Team',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 54,
          title: 'Update CI pipeline config',
          priority: 0,
          due_at: '2026-02-27T15:00:00Z',
          original_due_at: '2026-02-27T15:00:00Z',
          created_at: '2026-02-24T16:00:00Z',
          labels: ['work'],
          project_name: 'Platform Team',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 55,
          title: 'Daily standup',
          priority: 0,
          due_at: '2026-02-25T15:30:00Z',
          original_due_at: '2026-02-25T15:30:00Z',
          created_at: '2026-01-01T12:00:00Z',
          labels: ['work'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'The list is almost entirely work/Platform Team tasks. "Drop off library books" is a ' +
        'personal errand that stands out as the only non-work task. A good response: ' +
        '"that\'s your only non-work task on the board" or "a break from the code — everything ' +
        'else is Platform Team." Must observe the contrast between this personal errand and the ' +
        'work-heavy list.',
    },
  },

  // -------------------------------------------------------------------------
  // 5. Many similar undated tasks
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-similar-pile',
    feature: 'quick_take',
    description: 'New task joins a pile of similar undated tasks',
    input: {
      newTaskTitle: 'Fix login page accessibility',
      timezone: 'America/Chicago',
      tasks: [
        {
          id: 60,
          title: 'Fix checkout form validation',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: '2026-02-10T09:00:00Z',
          labels: ['bug'],
          project_name: 'Website Redesign',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 61,
          title: 'Fix mobile nav overflow',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: '2026-02-12T14:00:00Z',
          labels: ['bug'],
          project_name: 'Website Redesign',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 62,
          title: 'Fix image lazy loading on product pages',
          priority: 1,
          due_at: null,
          original_due_at: null,
          created_at: '2026-02-14T10:00:00Z',
          labels: ['bug'],
          project_name: 'Website Redesign',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 63,
          title: 'Fix dark mode toggle persistence',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: '2026-02-16T11:00:00Z',
          labels: ['bug'],
          project_name: 'Website Redesign',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 64,
          title: 'Fix footer link spacing',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: '2026-02-18T15:00:00Z',
          labels: ['bug'],
          project_name: 'Website Redesign',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 65,
          title: 'Fix search autocomplete delay',
          priority: 1,
          due_at: null,
          original_due_at: null,
          created_at: '2026-02-20T08:00:00Z',
          labels: ['bug'],
          project_name: 'Website Redesign',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 70,
          title: 'Morning standup',
          priority: 0,
          due_at: '2026-02-26T15:00:00Z',
          original_due_at: '2026-02-26T15:00:00Z',
          created_at: '2026-01-01T12:00:00Z',
          labels: [],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'The new task joins 6 existing "Fix ..." bug tasks in Website Redesign, all undated. ' +
        'A good response: "that\'s bug #7 in the Website Redesign backlog — none have dates yet" ' +
        'or "the fix pile grows — 7 undated bugs now." Must acknowledge the accumulating pattern ' +
        'of similar undated bug tasks. Should not suggest prioritization.',
    },
  },

  // -------------------------------------------------------------------------
  // 6. Empty inbox — first task
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-empty-inbox',
    feature: 'quick_take',
    description: 'User has zero existing tasks, this is the first task added',
    input: {
      newTaskTitle: 'Set up home office',
      timezone: 'America/Chicago',
      tasks: [],
    },
    requirements: {
      quality_notes:
        'The user has zero existing tasks. A good response acknowledges the clean slate: ' +
        '"starting fresh — your first task" or "empty list no more." Must not reference ' +
        'non-existent tasks or projects. Must not give generic advice. Should be brief ' +
        'and acknowledge the empty starting point.',
    },
  },

  // -------------------------------------------------------------------------
  // 7. Busy week — many tasks due this week
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-busy-week',
    feature: 'quick_take',
    description: 'User has 15+ tasks due this week, new one piles on',
    input: {
      newTaskTitle: 'Prep Friday presentation slides',
      timezone: 'America/Chicago',
      tasks: [
        // Monday Feb 23
        {
          id: 80,
          title: 'Team sync',
          priority: 1,
          due_at: '2026-02-23T15:00:00Z',
          original_due_at: '2026-02-23T15:00:00Z',
          created_at: '2026-02-20T09:00:00Z',
          labels: ['work'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=WEEKLY;BYDAY=MO',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 81,
          title: 'Client call with Apex Inc',
          priority: 2,
          due_at: '2026-02-23T18:00:00Z',
          original_due_at: '2026-02-23T18:00:00Z',
          created_at: '2026-02-19T10:00:00Z',
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        // Tuesday Feb 24
        {
          id: 82,
          title: 'Code review for PR #512',
          priority: 1,
          due_at: '2026-02-24T16:00:00Z',
          original_due_at: '2026-02-24T16:00:00Z',
          created_at: '2026-02-22T11:00:00Z',
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 83,
          title: 'Dentist cleaning',
          priority: 2,
          due_at: '2026-02-24T19:00:00Z',
          original_due_at: '2026-02-24T19:00:00Z',
          created_at: '2026-02-10T09:00:00Z',
          labels: ['health'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 84,
          title: 'Ship feature flag service',
          priority: 2,
          due_at: '2026-02-24T22:00:00Z',
          original_due_at: '2026-02-24T22:00:00Z',
          created_at: '2026-02-18T14:00:00Z',
          labels: ['work'],
          project_name: 'Platform Team',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        // Wednesday Feb 25 (today)
        {
          id: 85,
          title: 'Submit timesheet',
          priority: 1,
          due_at: '2026-02-25T17:00:00Z',
          original_due_at: '2026-02-25T17:00:00Z',
          created_at: '2026-02-23T08:00:00Z',
          labels: ['work'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=WEEKLY;BYDAY=WE',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 86,
          title: 'Review budget proposal',
          priority: 2,
          due_at: '2026-02-25T20:00:00Z',
          original_due_at: '2026-02-25T20:00:00Z',
          created_at: '2026-02-21T10:00:00Z',
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 87,
          title: 'Pick up prescription',
          priority: 1,
          due_at: '2026-02-25T22:00:00Z',
          original_due_at: '2026-02-25T22:00:00Z',
          created_at: '2026-02-23T11:00:00Z',
          labels: ['errand'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        // Thursday Feb 26
        {
          id: 88,
          title: 'Quarterly planning offsite',
          priority: 3,
          due_at: '2026-02-26T14:00:00Z',
          original_due_at: '2026-02-26T14:00:00Z',
          created_at: '2026-02-15T09:00:00Z',
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 89,
          title: 'Draft performance reviews',
          priority: 2,
          due_at: '2026-02-26T20:00:00Z',
          original_due_at: '2026-02-26T20:00:00Z',
          created_at: '2026-02-20T10:00:00Z',
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 90,
          title: 'Car oil change',
          priority: 0,
          due_at: '2026-02-26T22:00:00Z',
          original_due_at: '2026-02-26T22:00:00Z',
          created_at: '2026-02-15T12:00:00Z',
          labels: ['car'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        // Friday Feb 27
        {
          id: 91,
          title: 'Deploy release v3.0',
          priority: 3,
          due_at: '2026-02-27T16:00:00Z',
          original_due_at: '2026-02-27T16:00:00Z',
          created_at: '2026-02-19T14:00:00Z',
          labels: ['work'],
          project_name: 'Platform Team',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 92,
          title: 'Friday happy hour RSVP',
          priority: 0,
          due_at: '2026-02-27T19:00:00Z',
          original_due_at: '2026-02-27T19:00:00Z',
          created_at: '2026-02-24T10:00:00Z',
          labels: ['social'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 93,
          title: 'Weekly review',
          priority: 0,
          due_at: '2026-02-27T22:00:00Z',
          original_due_at: '2026-02-27T22:00:00Z',
          created_at: '2026-01-01T12:00:00Z',
          labels: [],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=WEEKLY;BYDAY=FR',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        // Saturday Feb 28
        {
          id: 94,
          title: 'Mow the lawn',
          priority: 0,
          due_at: '2026-02-28T16:00:00Z',
          original_due_at: '2026-02-28T16:00:00Z',
          created_at: '2026-02-23T09:00:00Z',
          labels: ['home'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'The user has 15 tasks spanning Mon-Sat this week, and the new "Prep Friday presentation ' +
        'slides" adds to an already packed schedule. A good response: "packed week — that makes ' +
        '16 tasks before Sunday" or "Friday already has a deploy and happy hour, now slides too." ' +
        'Must reference the volume of tasks this week or how full the schedule is.',
    },
  },

  // -------------------------------------------------------------------------
  // 8. Recurring context — one-off alongside routines
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-recurring-context',
    feature: 'quick_take',
    description:
      'New one-off task alongside recurring routines — note the one-off or relate to routines',
    input: {
      newTaskTitle: 'Book vet appointment for Luna',
      timezone: 'America/Chicago',
      tasks: [
        {
          id: 100,
          title: 'Morning meditation',
          priority: 0,
          due_at: '2026-02-26T13:00:00Z',
          original_due_at: '2026-02-26T13:00:00Z',
          created_at: '2026-01-01T12:00:00Z',
          labels: ['wellness'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 101,
          title: 'Walk the dog',
          priority: 0,
          due_at: '2026-02-26T14:00:00Z',
          original_due_at: '2026-02-26T14:00:00Z',
          created_at: '2026-01-01T12:00:00Z',
          labels: ['pet'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 102,
          title: 'Take vitamins',
          priority: 0,
          due_at: '2026-02-26T13:30:00Z',
          original_due_at: '2026-02-26T13:30:00Z',
          created_at: '2026-01-01T12:00:00Z',
          labels: ['health'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 103,
          title: 'Check email',
          priority: 0,
          due_at: '2026-02-26T15:00:00Z',
          original_due_at: '2026-02-26T15:00:00Z',
          created_at: '2026-01-01T12:00:00Z',
          labels: ['work'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 104,
          title: 'Evening journal',
          priority: 0,
          due_at: '2026-02-26T03:00:00Z',
          original_due_at: '2026-02-26T03:00:00Z',
          created_at: '2026-01-01T12:00:00Z',
          labels: ['wellness'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 105,
          title: 'Weekly meal prep',
          priority: 0,
          due_at: '2026-03-01T16:00:00Z',
          original_due_at: '2026-03-01T16:00:00Z',
          created_at: '2026-01-01T12:00:00Z',
          labels: ['home'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=WEEKLY;BYDAY=SU',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 106,
          title: 'Refill dog food',
          priority: 1,
          due_at: '2026-02-28T15:00:00Z',
          original_due_at: '2026-02-28T15:00:00Z',
          created_at: '2026-02-20T10:00:00Z',
          labels: ['pet'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'The list is mostly daily routines (meditation, dog walk, vitamins, email, journal). ' +
        'The new task "Book vet appointment for Luna" is a one-off pet task. A good response ' +
        'could relate it to the existing dog walk routine or note that the user has another pet ' +
        'task (refill dog food): "Luna\'s got a busy week — dog food refill is due Saturday too" ' +
        'or "that\'s 2 pet tasks now alongside your daily routines." Must show awareness of ' +
        'the routine-heavy list and/or the pet context.',
    },
  },
]
