/**
 * Quick Take scenarios
 *
 * Tests the Quick Take feature which generates a one-liner AI commentary
 * when a task is created, cross-referencing existing tasks. Unlike other
 * features, quick take returns plain text (a single sentence), not
 * structured JSON.
 *
 * Each scenario provides a newTaskTitle and a set of existing tasks that
 * create a specific context the AI should pick up on.
 */

import type { AITestScenario } from '../types'
import {
  daysAgo,
  daysAgoAt,
  weeksAgo,
  monthsAgo,
  todayAt,
  tomorrowAt,
  daysFromNowAt,
} from '../helpers/dates'

const tz = 'America/Chicago'

export const quickTakeScenarios: AITestScenario[] = [
  // -------------------------------------------------------------------------
  // 1. Cross-reference by project
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-project-crossref',
    feature: 'quick_take',
    description: 'New task matches existing project tasks — should cross-reference by project',
    input: {
      newTaskTitle: 'Draft Acme Q1 report',
      timezone: 'America/Chicago',
      tasks: [
        {
          id: 1,
          title: 'Review Acme contract renewal',
          priority: 2,
          due_at: todayAt(9, 0, tz),
          original_due_at: todayAt(9, 0, tz),
          created_at: daysAgo(6),
          labels: [],
          project_name: 'Acme Corp',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 2,
          title: 'Send Acme invoice #4821',
          priority: 1,
          due_at: tomorrowAt(9, 0, tz),
          original_due_at: tomorrowAt(9, 0, tz),
          created_at: daysAgo(4),
          labels: [],
          project_name: 'Acme Corp',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 3,
          title: 'Prepare Acme demo environment',
          priority: 0,
          due_at: daysFromNowAt(2, 14, 0, tz),
          original_due_at: daysFromNowAt(2, 14, 0, tz),
          created_at: daysAgo(3),
          labels: [],
          project_name: 'Acme Corp',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 10,
          title: 'Buy groceries',
          priority: 0,
          due_at: daysAgoAt(1, 16, 0, tz),
          original_due_at: daysAgoAt(1, 16, 0, tz),
          created_at: daysAgo(2),
          labels: ['errand'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 11,
          title: 'Morning run',
          priority: 0,
          due_at: todayAt(7, 0, tz),
          original_due_at: todayAt(7, 0, tz),
          created_at: monthsAgo(2),
          labels: ['health'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 12,
          title: 'Call dentist for appointment',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: daysAgo(8),
          labels: [],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 13,
          title: 'Update resume',
          priority: 1,
          due_at: daysFromNowAt(3, 9, 0, tz),
          original_due_at: daysFromNowAt(3, 9, 0, tz),
          created_at: daysAgo(6),
          labels: [],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'Should cross-reference the 3 existing Acme Corp tasks. A good response shows awareness ' +
        'of the Acme cluster: "Acme week — this makes it a theme" or "4th Acme task on the board." ' +
        'Could also contrast with the non-work tasks. Must not be generic ("task added!"). ' +
        'Must reference the Acme project or similar tasks. Max 25 words.',
    },
  },

  // -------------------------------------------------------------------------
  // 2. Cross-reference by timing — busy day
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-busy-day',
    feature: 'quick_take',
    description: 'New task fills up an already busy day — should note the crowding',
    input: {
      newTaskTitle: 'Team standup prep',
      timezone: 'America/Chicago',
      tasks: [
        {
          id: 20,
          title: 'Dentist appointment',
          priority: 2,
          due_at: todayAt(9, 0, tz),
          original_due_at: todayAt(9, 0, tz),
          created_at: daysAgo(12),
          labels: ['health'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 21,
          title: 'Submit expense report',
          priority: 1,
          due_at: todayAt(11, 0, tz),
          original_due_at: todayAt(11, 0, tz),
          created_at: daysAgo(7),
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 22,
          title: 'Pick up dry cleaning',
          priority: 0,
          due_at: todayAt(14, 0, tz),
          original_due_at: todayAt(14, 0, tz),
          created_at: daysAgo(5),
          labels: ['errand'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 23,
          title: 'Review pull request',
          priority: 1,
          due_at: todayAt(15, 0, tz),
          original_due_at: todayAt(15, 0, tz),
          created_at: daysAgo(3),
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 30,
          title: 'Weekly grocery run',
          priority: 0,
          due_at: tomorrowAt(9, 0, tz),
          original_due_at: tomorrowAt(9, 0, tz),
          created_at: daysAgo(7),
          labels: ['errand'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=WEEKLY',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 31,
          title: 'Read chapter 5',
          priority: 0,
          due_at: tomorrowAt(16, 0, tz),
          original_due_at: tomorrowAt(16, 0, tz),
          created_at: daysAgo(5),
          labels: [],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'Today is getting busy — 4 existing tasks due today and now a 5th. ' +
        'A good response observes the crowded day: "today is getting crowded" or ' +
        '"busy day — you already had 4 things due." Could name specific tasks for flavor. ' +
        'Must reference the busy nature of the day. Max 25 words.',
    },
  },

  // -------------------------------------------------------------------------
  // 3. No due date observation
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-no-due-date',
    feature: 'quick_take',
    description: 'New task has no due date — should comment on it sitting in inbox',
    input: {
      newTaskTitle: 'Research standing desks',
      timezone: 'America/Chicago',
      tasks: [
        {
          id: 40,
          title: 'File taxes',
          priority: 3,
          due_at: daysFromNowAt(17, 9, 0, tz),
          original_due_at: daysFromNowAt(17, 9, 0, tz),
          created_at: daysAgo(25),
          labels: ['finance'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 41,
          title: 'Morning standup',
          priority: 0,
          due_at: todayAt(9, 0, tz),
          original_due_at: todayAt(9, 0, tz),
          created_at: monthsAgo(2),
          labels: ['work'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 42,
          title: 'Call insurance about deductible',
          priority: 1,
          due_at: daysFromNowAt(2, 10, 0, tz),
          original_due_at: daysFromNowAt(2, 10, 0, tz),
          created_at: daysAgo(8),
          labels: [],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 43,
          title: 'Replace furnace filter',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: daysAgo(16),
          labels: ['home'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 44,
          title: 'Plan weekend trip',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: daysAgo(11),
          labels: [],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 45,
          title: 'Review quarterly goals',
          priority: 2,
          due_at: daysFromNowAt(3, 9, 0, tz),
          original_due_at: daysFromNowAt(3, 9, 0, tz),
          created_at: daysAgo(6),
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'The new task "Research standing desks" has no due date. A good response ' +
        'observes the undated status: "no due date — joins 2 others floating in your inbox" ' +
        'or contrasts it with the scheduled tasks. Could reference the other undated tasks ' +
        '(IDs 43, 44). Must reference the lack of a due date or inbox. Max 25 words.',
    },
  },

  // -------------------------------------------------------------------------
  // 4. Solo task in a category
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-solo-category',
    feature: 'quick_take',
    description: 'New task is the only one of its kind — should note its uniqueness',
    input: {
      newTaskTitle: 'Drop off library books',
      timezone: 'America/Chicago',
      tasks: [
        {
          id: 50,
          title: 'Sprint planning meeting',
          priority: 2,
          due_at: daysAgoAt(1, 9, 0, tz),
          original_due_at: daysAgoAt(1, 9, 0, tz),
          created_at: daysAgo(6),
          labels: ['work'],
          project_name: 'Platform Team',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 51,
          title: 'Deploy v2.3 to staging',
          priority: 2,
          due_at: daysAgoAt(1, 12, 0, tz),
          original_due_at: daysAgoAt(1, 12, 0, tz),
          created_at: daysAgo(3),
          labels: ['work'],
          project_name: 'Platform Team',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 52,
          title: 'Write API docs for auth module',
          priority: 1,
          due_at: todayAt(14, 0, tz),
          original_due_at: todayAt(14, 0, tz),
          created_at: daysAgo(4),
          labels: ['work'],
          project_name: 'Platform Team',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 53,
          title: 'Code review: login flow refactor',
          priority: 1,
          due_at: todayAt(11, 0, tz),
          original_due_at: todayAt(11, 0, tz),
          created_at: daysAgo(2),
          labels: ['work'],
          project_name: 'Platform Team',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 54,
          title: 'Update CI pipeline config',
          priority: 0,
          due_at: tomorrowAt(9, 0, tz),
          original_due_at: tomorrowAt(9, 0, tz),
          created_at: daysAgo(2),
          labels: ['work'],
          project_name: 'Platform Team',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 55,
          title: 'Daily standup',
          priority: 0,
          due_at: daysAgoAt(1, 9, 30, tz),
          original_due_at: daysAgoAt(1, 9, 30, tz),
          created_at: monthsAgo(2),
          labels: ['work'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'The list is almost entirely work/Platform Team tasks. "Drop off library books" is a ' +
        'personal errand that stands out as the only non-work task. A good response shows ' +
        'contrast: "your only personal errand in a sea of Platform Team work" or ' +
        '"a break from the code." Must observe the contrast with the work-heavy list. Max 25 words.',
    },
  },

  // -------------------------------------------------------------------------
  // 5. Many similar undated tasks
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-similar-pile',
    feature: 'quick_take',
    description: 'New task joins a pile of similar undated tasks',
    input: {
      newTaskTitle: 'Fix login page accessibility',
      timezone: 'America/Chicago',
      tasks: [
        {
          id: 60,
          title: 'Fix checkout form validation',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: daysAgo(16),
          labels: ['bug'],
          project_name: 'Website Redesign',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 61,
          title: 'Fix mobile nav overflow',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: weeksAgo(2),
          labels: ['bug'],
          project_name: 'Website Redesign',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 62,
          title: 'Fix image lazy loading on product pages',
          priority: 1,
          due_at: null,
          original_due_at: null,
          created_at: daysAgo(12),
          labels: ['bug'],
          project_name: 'Website Redesign',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 63,
          title: 'Fix dark mode toggle persistence',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: daysAgo(10),
          labels: ['bug'],
          project_name: 'Website Redesign',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 64,
          title: 'Fix footer link spacing',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: daysAgo(8),
          labels: ['bug'],
          project_name: 'Website Redesign',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 65,
          title: 'Fix search autocomplete delay',
          priority: 1,
          due_at: null,
          original_due_at: null,
          created_at: daysAgo(6),
          labels: ['bug'],
          project_name: 'Website Redesign',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 70,
          title: 'Morning standup',
          priority: 0,
          due_at: todayAt(9, 0, tz),
          original_due_at: todayAt(9, 0, tz),
          created_at: monthsAgo(2),
          labels: [],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'The new task joins 6 existing "Fix ..." bug tasks in Website Redesign, all undated. ' +
        'A good response: "another fix for Website Redesign — the bug backlog grows" or ' +
        '"7 undated bugs and counting." Must acknowledge the accumulating pattern ' +
        'of similar undated bug tasks. Should not suggest prioritization. Max 25 words.',
    },
  },

  // -------------------------------------------------------------------------
  // 6. Empty inbox — first task
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-empty-inbox',
    feature: 'quick_take',
    description: 'User has zero existing tasks, this is the first task added',
    input: {
      newTaskTitle: 'Set up home office',
      timezone: 'America/Chicago',
      tasks: [],
    },
    requirements: {
      quality_notes:
        'The user has zero existing tasks. A good response acknowledges the clean slate: ' +
        '"first task on an empty board" or "starting fresh." Must not reference ' +
        'non-existent tasks or projects. Must not give generic advice. Should be brief ' +
        'and acknowledge the empty starting point. Max 25 words.',
    },
  },

  // -------------------------------------------------------------------------
  // 7. Busy week — many tasks due this week
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-busy-week',
    feature: 'quick_take',
    description: 'User has 15+ tasks due this week, new one piles on',
    input: {
      newTaskTitle: 'Prep Friday presentation slides',
      timezone: 'America/Chicago',
      tasks: [
        // Monday Feb 23
        {
          id: 80,
          title: 'Team sync',
          priority: 1,
          due_at: daysAgoAt(3, 9, 0, tz),
          original_due_at: daysAgoAt(3, 9, 0, tz),
          created_at: daysAgo(6),
          labels: ['work'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=WEEKLY;BYDAY=MO',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 81,
          title: 'Client call with Apex Inc',
          priority: 2,
          due_at: daysAgoAt(3, 12, 0, tz),
          original_due_at: daysAgoAt(3, 12, 0, tz),
          created_at: daysAgo(7),
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        // Tuesday Feb 24
        {
          id: 82,
          title: 'Code review for PR #512',
          priority: 1,
          due_at: daysAgoAt(2, 10, 0, tz),
          original_due_at: daysAgoAt(2, 10, 0, tz),
          created_at: daysAgo(4),
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 83,
          title: 'Dentist cleaning',
          priority: 2,
          due_at: daysAgoAt(2, 13, 0, tz),
          original_due_at: daysAgoAt(2, 13, 0, tz),
          created_at: daysAgo(16),
          labels: ['health'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 84,
          title: 'Ship feature flag service',
          priority: 2,
          due_at: daysAgoAt(2, 16, 0, tz),
          original_due_at: daysAgoAt(2, 16, 0, tz),
          created_at: daysAgo(8),
          labels: ['work'],
          project_name: 'Platform Team',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        // Wednesday Feb 25 (today)
        {
          id: 85,
          title: 'Submit timesheet',
          priority: 1,
          due_at: daysAgoAt(1, 11, 0, tz),
          original_due_at: daysAgoAt(1, 11, 0, tz),
          created_at: daysAgo(3),
          labels: ['work'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=WEEKLY;BYDAY=WE',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 86,
          title: 'Review budget proposal',
          priority: 2,
          due_at: daysAgoAt(1, 14, 0, tz),
          original_due_at: daysAgoAt(1, 14, 0, tz),
          created_at: daysAgo(5),
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 87,
          title: 'Pick up prescription',
          priority: 1,
          due_at: daysAgoAt(1, 16, 0, tz),
          original_due_at: daysAgoAt(1, 16, 0, tz),
          created_at: daysAgo(3),
          labels: ['errand'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        // Thursday Feb 26
        {
          id: 88,
          title: 'Quarterly planning offsite',
          priority: 3,
          due_at: todayAt(8, 0, tz),
          original_due_at: todayAt(8, 0, tz),
          created_at: daysAgo(11),
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 89,
          title: 'Draft performance reviews',
          priority: 2,
          due_at: todayAt(14, 0, tz),
          original_due_at: todayAt(14, 0, tz),
          created_at: daysAgo(6),
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 90,
          title: 'Car oil change',
          priority: 0,
          due_at: todayAt(16, 0, tz),
          original_due_at: todayAt(16, 0, tz),
          created_at: daysAgo(11),
          labels: ['car'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        // Friday Feb 27
        {
          id: 91,
          title: 'Deploy release v3.0',
          priority: 3,
          due_at: tomorrowAt(10, 0, tz),
          original_due_at: tomorrowAt(10, 0, tz),
          created_at: daysAgo(7),
          labels: ['work'],
          project_name: 'Platform Team',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 92,
          title: 'Friday happy hour RSVP',
          priority: 0,
          due_at: tomorrowAt(13, 0, tz),
          original_due_at: tomorrowAt(13, 0, tz),
          created_at: daysAgo(2),
          labels: ['social'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 93,
          title: 'Weekly review',
          priority: 0,
          due_at: tomorrowAt(16, 0, tz),
          original_due_at: tomorrowAt(16, 0, tz),
          created_at: monthsAgo(2),
          labels: [],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=WEEKLY;BYDAY=FR',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        // Saturday Feb 28
        {
          id: 94,
          title: 'Mow the lawn',
          priority: 0,
          due_at: daysFromNowAt(2, 10, 0, tz),
          original_due_at: daysFromNowAt(2, 10, 0, tz),
          created_at: daysAgo(3),
          labels: ['home'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'The user has 15 tasks spanning Mon-Sat this week, and the new "Prep Friday presentation ' +
        'slides" adds to an already packed schedule. A good response could reference the specific ' +
        'Friday context: "Friday already has a deploy and happy hour, now slides too" or note ' +
        'the packed week overall. Must reference volume or specific day context. Max 25 words.',
    },
  },

  // -------------------------------------------------------------------------
  // 8. Recurring context — one-off alongside routines
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-recurring-context',
    feature: 'quick_take',
    description:
      'New one-off task alongside recurring routines — note the one-off or relate to routines',
    input: {
      newTaskTitle: 'Book vet appointment for Luna',
      timezone: 'America/Chicago',
      tasks: [
        {
          id: 100,
          title: 'Morning meditation',
          priority: 0,
          due_at: todayAt(7, 0, tz),
          original_due_at: todayAt(7, 0, tz),
          created_at: monthsAgo(2),
          labels: ['wellness'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 101,
          title: 'Walk the dog',
          priority: 0,
          due_at: todayAt(8, 0, tz),
          original_due_at: todayAt(8, 0, tz),
          created_at: monthsAgo(2),
          labels: ['pet'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 102,
          title: 'Take vitamins',
          priority: 0,
          due_at: todayAt(7, 30, tz),
          original_due_at: todayAt(7, 30, tz),
          created_at: monthsAgo(2),
          labels: ['health'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 103,
          title: 'Check email',
          priority: 0,
          due_at: todayAt(9, 0, tz),
          original_due_at: todayAt(9, 0, tz),
          created_at: monthsAgo(2),
          labels: ['work'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 104,
          title: 'Evening journal',
          priority: 0,
          due_at: daysAgoAt(1, 21, 0, tz),
          original_due_at: daysAgoAt(1, 21, 0, tz),
          created_at: monthsAgo(2),
          labels: ['wellness'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 105,
          title: 'Weekly meal prep',
          priority: 0,
          due_at: daysFromNowAt(3, 10, 0, tz),
          original_due_at: daysFromNowAt(3, 10, 0, tz),
          created_at: monthsAgo(2),
          labels: ['home'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=WEEKLY;BYDAY=SU',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 106,
          title: 'Refill dog food',
          priority: 1,
          due_at: daysFromNowAt(2, 9, 0, tz),
          original_due_at: daysFromNowAt(2, 9, 0, tz),
          created_at: daysAgo(6),
          labels: ['pet'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'The list is mostly daily routines (meditation, dog walk, vitamins, email, journal). ' +
        'The new task "Book vet appointment for Luna" is a one-off pet task. A good response ' +
        'could note it as a one-off among routines, or relate to the pet context (dog walk, ' +
        'dog food refill). Must show awareness of the routine-heavy list and/or pet context. ' +
        'Max 25 words.',
    },
  },

  // -------------------------------------------------------------------------
  // 9. Contrast scenario — personal task in work-dominated list
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-contrast-personal',
    feature: 'quick_take',
    description:
      'Personal task added to a work-dominated list — should produce contrast, not count',
    input: {
      newTaskTitle: 'Buy birthday present for mom',
      timezone: 'America/Chicago',
      tasks: [
        {
          id: 200,
          title: 'Finalize Q1 roadmap',
          priority: 3,
          due_at: todayAt(9, 0, tz),
          original_due_at: todayAt(9, 0, tz),
          created_at: daysAgo(6),
          labels: ['work'],
          project_name: 'Product',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 201,
          title: 'Review design mockups',
          priority: 2,
          due_at: todayAt(12, 0, tz),
          original_due_at: todayAt(12, 0, tz),
          created_at: daysAgo(4),
          labels: ['work'],
          project_name: 'Product',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 202,
          title: 'Write engineering RFC',
          priority: 2,
          due_at: tomorrowAt(9, 0, tz),
          original_due_at: tomorrowAt(9, 0, tz),
          created_at: daysAgo(3),
          labels: ['work'],
          project_name: 'Product',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 203,
          title: 'Sprint retro prep',
          priority: 1,
          due_at: tomorrowAt(14, 0, tz),
          original_due_at: tomorrowAt(14, 0, tz),
          created_at: daysAgo(2),
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 204,
          title: 'Update team wiki',
          priority: 0,
          due_at: daysFromNowAt(2, 9, 0, tz),
          original_due_at: daysFromNowAt(2, 9, 0, tz),
          created_at: daysAgo(1),
          labels: ['work'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 205,
          title: 'Daily standup',
          priority: 0,
          due_at: todayAt(9, 30, tz),
          original_due_at: todayAt(9, 30, tz),
          created_at: monthsAgo(2),
          labels: ['work'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'All 6 existing tasks are work-related (5 with "work" label, 3 in "Product" project). ' +
        '"Buy birthday present for mom" is a personal task that contrasts sharply. A good response ' +
        'observes the contrast: "your only non-work item on the list" or "a personal touch among ' +
        'all those Product tasks." Must NOT just count tasks. Must observe the contrast between ' +
        'personal and work. Max 25 words.',
    },
  },

  // -------------------------------------------------------------------------
  // 10. Day-detail scenario — task added to a day with specific named tasks
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-day-detail',
    feature: 'quick_take',
    description:
      'Task added to a day with specific named tasks — should mention context, not just count',
    input: {
      newTaskTitle: 'Prep slides for all-hands',
      timezone: 'America/Chicago',
      tasks: [
        {
          id: 210,
          title: 'Deploy v4.0 to production',
          priority: 3,
          due_at: todayAt(10, 0, tz),
          original_due_at: todayAt(10, 0, tz),
          created_at: daysAgo(7),
          labels: ['work'],
          project_name: 'Platform Team',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 211,
          title: 'Lunch with Sarah',
          priority: 1,
          due_at: todayAt(12, 0, tz),
          original_due_at: todayAt(12, 0, tz),
          created_at: daysAgo(3),
          labels: [],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 212,
          title: 'Team happy hour',
          priority: 0,
          due_at: todayAt(17, 0, tz),
          original_due_at: todayAt(17, 0, tz),
          created_at: daysAgo(2),
          labels: ['social'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 213,
          title: 'Weekly grocery run',
          priority: 0,
          due_at: tomorrowAt(9, 0, tz),
          original_due_at: tomorrowAt(9, 0, tz),
          created_at: daysAgo(7),
          labels: ['errand'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=WEEKLY',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'Today already has a deploy, lunch with Sarah, and happy hour. Adding slides ' +
        'makes it a packed day with diverse tasks. A good response references the specific things ' +
        'on the day: "today already has a deploy, lunch, and happy hour — now slides too" or ' +
        '"busy day — a deploy and happy hour, and now presentation prep." Must mention at ' +
        'least one specific existing task by name or type, not just a count. Max 25 words.',
    },
  },

  // -------------------------------------------------------------------------
  // 11. Backlog growth — adding to a growing undated backlog
  // -------------------------------------------------------------------------
  {
    id: 'quick-take-backlog-growth',
    feature: 'quick_take',
    description: 'Adding another undated task to a growing backlog — should comment on the pattern',
    input: {
      newTaskTitle: 'Reorganize garage shelves',
      timezone: 'America/Chicago',
      tasks: [
        {
          id: 220,
          title: 'Clean out hall closet',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: daysAgo(25),
          labels: ['home'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 221,
          title: 'Fix leaky faucet',
          priority: 1,
          due_at: null,
          original_due_at: null,
          created_at: weeksAgo(3),
          labels: ['home'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 222,
          title: 'Paint guest bedroom',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: daysAgo(18),
          labels: ['home'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 223,
          title: 'Replace smoke detector batteries',
          priority: 2,
          due_at: null,
          original_due_at: null,
          created_at: weeksAgo(2),
          labels: ['home'],
          project_name: null,
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 224,
          title: 'Morning run',
          priority: 0,
          due_at: todayAt(7, 0, tz),
          original_due_at: todayAt(7, 0, tz),
          created_at: monthsAgo(2),
          labels: ['health'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 225,
          title: 'Team standup',
          priority: 0,
          due_at: todayAt(9, 0, tz),
          original_due_at: todayAt(9, 0, tz),
          created_at: monthsAgo(2),
          labels: ['work'],
          project_name: null,
          is_recurring: true,
          rrule: 'FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        '4 existing undated home tasks form a clear pattern — all home improvement projects ' +
        'without deadlines. "Reorganize garage shelves" is another one. A good response: ' +
        '"the home project list keeps growing — 5 with no dates now" or "another home task ' +
        'without a deadline, joining 4 others." Must acknowledge the growing undated home backlog. ' +
        'Max 25 words.',
    },
  },

  // -------------------------------------------------------------------------
  // 12. Regression: demo user data — personal errand in work-heavy list
  // -------------------------------------------------------------------------
  // Mirrors the exact demo user task data from scripts/seed-demo.ts.
  // The original failure: the model said "your only personal errand among 8
  // Client Work tasks" when 4 of 13 active tasks had no project association
  // (i.e., were not Client Work). This scenario prevents that regression.
  {
    id: 'quick-take-regression-demo',
    feature: 'quick_take',
    description:
      'Regression: personal errand added to work-heavy demo list — must not fabricate composition claims',
    input: {
      newTaskTitle: 'pick up washer fluid',
      timezone: 'America/Chicago',
      tasks: [
        // ── Try It project (4 tasks, 3 undated + 1 overdue) ──
        {
          id: 1,
          title:
            "Try adding a task — type 'Set up weekly standup every Monday at 10am' in the box above",
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: daysAgo(3),
          labels: [],
          project_name: 'Try It',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 2,
          title:
            "Try voice input — say 'Review deployment pipeline Friday afternoon medium priority'",
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: daysAgo(3),
          labels: [],
          project_name: 'Try It',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 3,
          title: 'Learn about OpenTask',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: daysAgo(3),
          labels: [],
          project_name: 'Try It',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 4,
          title: 'Try completing this task — swipe right or tap the circle',
          priority: 0,
          due_at: daysFromNowAt(-1, 15, 0, tz),
          original_due_at: daysFromNowAt(-1, 15, 0, tz),
          created_at: daysAgo(2),
          labels: [],
          project_name: 'Try It',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        // ── Client Work project (8 tasks, 7 dated + 1 undated) ──
        {
          id: 5,
          title: 'Prepare implementation plan for client onboarding',
          priority: 3,
          due_at: tomorrowAt(10, 0, tz),
          original_due_at: tomorrowAt(10, 0, tz),
          created_at: daysAgo(4),
          labels: [],
          project_name: 'Client Work',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 6,
          title: 'Build MCP server for client CRM integration',
          priority: 2,
          due_at: daysFromNowAt(4, 14, 0, tz),
          original_due_at: daysFromNowAt(4, 14, 0, tz),
          created_at: daysAgo(5),
          labels: [],
          project_name: 'Client Work',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 7,
          title: 'Set up Claude Code workflow for automated testing',
          priority: 2,
          due_at: daysFromNowAt(3, 15, 0, tz),
          original_due_at: daysFromNowAt(3, 15, 0, tz),
          created_at: daysAgo(5),
          labels: [],
          project_name: 'Client Work',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 8,
          title: 'Schedule intro call — new AI automation project',
          priority: 2,
          due_at: daysFromNowAt(3, 14, 0, tz),
          original_due_at: daysFromNowAt(3, 14, 0, tz),
          created_at: daysAgo(3),
          labels: [],
          project_name: 'Client Work',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 9,
          title: 'Draft project scope for RAG pipeline integration',
          priority: 1,
          due_at: null,
          original_due_at: null,
          created_at: daysAgo(22),
          labels: [],
          project_name: 'Client Work',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 10,
          title: 'Review pull request — API authentication updates',
          priority: 3,
          due_at: tomorrowAt(17, 0, tz),
          original_due_at: tomorrowAt(17, 0, tz),
          created_at: daysAgo(1),
          labels: [],
          project_name: 'Client Work',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 11,
          title: 'Client status update',
          priority: 1,
          due_at: daysFromNowAt(2, 10, 0, tz),
          original_due_at: daysFromNowAt(2, 10, 0, tz),
          created_at: daysAgo(7),
          labels: [],
          project_name: 'Client Work',
          is_recurring: true,
          rrule: 'FREQ=WEEKLY;BYDAY=MO,TH;BYHOUR=10;BYMINUTE=0',
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        {
          id: 12,
          title: 'Follow up on proposal — workflow automation project',
          priority: 2,
          due_at: daysFromNowAt(3, 9, 0, tz),
          original_due_at: daysFromNowAt(3, 9, 0, tz),
          created_at: daysAgo(4),
          labels: [],
          project_name: 'Client Work',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
        // ── Inbox (1 task, undated) ──
        {
          id: 13,
          title: 'Want to work together? Reach out to Trent at trent@mcnitt.io',
          priority: 0,
          due_at: null,
          original_due_at: null,
          created_at: daysAgo(3),
          labels: [],
          project_name: 'Inbox',
          is_recurring: false,
          rrule: null,
          notes: null,
          recurrence_mode: 'from_due' as const,
        },
      ],
    },
    requirements: {
      quality_notes:
        'REGRESSION TEST — the original failure was: "your only personal errand among 8 Client ' +
        'Work tasks." This was factually wrong: 4 of 13 active tasks were not Client Work (3 Try It ' +
        '+ 1 Inbox), and none had a "personal errand" label. The new task "pick up washer fluid" is ' +
        'a personal errand being added to a work-heavy list. A good response notices the contrast ' +
        '(personal task among professional ones) but states it accurately — e.g., "a personal errand ' +
        'joining a list dominated by Client Work." Must NOT claim "only personal errand," "only ' +
        'errand," or "first personal task." Must not fabricate numbers or categories not present in ' +
        'the data. Max 25 words.',
    },
  },
]
